name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Discord bot
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
              mkdir cyto_live
              cd cyto_live
              git clone git@github.com:SammyDeAgent/cytokine-harmony.git
              cd cytokine-harmony
              git add -A
              git commit -a -m 'Commiting linux dependencies'
              git pull origin master
              rm -rf node_modules/
              npm update
              pm2 start jukebox.js
              pm2 restart jukebox
              pm2 save
              echo "Deploy to Digital Ocean Droplet successful."